
provider "google" {
  project = "kheopsys-lab"
  region  = "us-central1"
  zone    = "us-central1-a"
}


resource "google_compute_subnetwork" "airflow_demo_subnetowrk" {
 name          = "airflow-demo-subnetowrk" 
 ip_cidr_range = "10.0.2.0/28"
 region        = "us-central1"
 network       = "default"
}

resource "google_compute_firewall" "airflow_demo_allow_ssh" {
  name    = "airflow-demo-firewall-ssh"
  network = "default"

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

  source_ranges = ["0.0.0.0/0"]
}

resource "google_compute_firewall" "airflow_demo_allow_http" {
  name    = "airflow-demo-firewall-http"
  network = "default"

  allow {
    protocol = "tcp"
    ports    = ["8080"]
  }

  source_ranges = ["0.0.0.0/0"]
}


resource "google_compute_instance" "airflow_demo_vm" {
  name         = "airflow-demo-vm"
  machine_type = "e2-standard-8"
  zone         = "us-central1-a"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-11"
      size  = 100
    }
  }

  network_interface {
    network = "default"
    subnetwork = google_compute_subnetwork.airflow_demo_subnetowrk.name

    access_config {
    }
  }

   metadata_startup_script = <<-EOF
    # Update and install dependencies
    apt-get update
    apt-get install -y apt-transport-https ca-certificates curl gnupg
    apt-get install -y lsb-release software-properties-common

    # Add Docker GPG key and repository
    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    sudo echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    
    # Install Docker and Docker Compose
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io
    sudo systemctl start docker
    sudo systemctl enable docker
    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose

    # Configure Docker with GCP
    sudo gcloud auth configure-docker gcr.io

    # Create airflow user and set up directories
    sudo useradd -m -s /bin/bash airflow
    sudo usermod -aG docker airflow

    sudo mkdir -p /airflow/dags /airflow/logs /airflow/plugins /airflow/config /airflow/dags/jars
    sudo chown -R airflow:airflow /airflow

    # Download necessary jars
    sudo wget https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop3-2.2.2.jar 
    sudo wget https://jdbc.postgresql.org/download/postgresql-42.2.5.jar 

    sudo mv gcs-connector-hadoop3-2.2.2.jar /airflow/dags/jars/
    sudo mv postgresql-42.2.5.jar /airflow/dags/jars/

    # Clone Airflow artifacts repository
    sudo -u airflow git clone https://github.com/kheopsys/Data-Platform-Artifacts.git  # Reference here https://airflow.apache.org/docs/apache-airflow/2.9.1
    sudo cp /home/airflow/Data-Platform-Artifacts/airflow/docker-compose.yaml /airflow
    sudo cp /home/airflow/Data-Platform-Artifacts/airflow/Dockerfile /airflow
    sudo cp /home/airflow/Data-Platform-Artifacts/airflow/requirements.txt /airflow
    sudo echo "AIRFLOW_UID=$(id -u airflow)" > /airflow/.env

    print('start')
    
    # Build and start Airflow Docker containers as airflow user
    sudo -u airflow bash <<EOF
    cd /airflow
    docker build .
    docker-compose up -d
    EOF

  service_account {
    email  = "service-account-id@kheopsys-lab.iam.gserviceaccount.com"
    scopes = ["https://www.googleapis.com/auth/cloud-platform"]
  }

  tags = ["airflow"]
}

output "airflow_demo_vm_ip" {
  value = google_compute_instance.airflow_demo_vm.network_interface[0].access_config[0].nat_ip
}
